# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  - release/macos

pr:
  - release/macos

pool:
  vmImage: "macOS-10.13"

steps:
  - bash: "./release.sh"
    workingDirectory: macosx
  - task: DownloadSecureFile@1
    inputs:
      secureFile: "ci-secret-file.txt"
  - bash: "npm i && node ./upload_script.js mac ../macosx/Castle.pkg"
    workingDirectory: ci
