version: 2
jobs:
  build:
    branches:
      only:
        - release/macos
        - ben/notarize-macos

    macos:
      xcode: "10.1.0"

    steps:
      - checkout

      - run:
          name: Build and Upload
          command: cd macosx && ./release.sh --no-upload

      - store_artifacts:
          path: /tmp/castle-notarize-artifacts